version: 0.2

env:
  variables:
    ENV: "dev"
    S3_ARC: "prj-artifact-pipeline-dev"
    SRC_NODE: "api"

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - echo "Build to ${ENV}"
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 498907343309.dkr.ecr.ap-southeast-1.amazonaws.com

  build:
    commands:
      - chmod a+x ${CODEBUILD_SRC_DIR}/codebuild/api/build.sh
      - ${CODEBUILD_SRC_DIR}/codebuild/api/build.sh
      - docker images

  post_build:
    commands:
      - chmod a+x ${CODEBUILD_SRC_DIR}/codebuild/api/postbuild.sh
      - ${CODEBUILD_SRC_DIR}/codebuild/api/postbuild.sh

artifacts:
  files:
    - ${CODEBUILD_SRC_DIR}/codedeploy/appspec.yml
    - ${CODEBUILD_SRC_DIR}/codedeploy/taskdef.json
  discard-paths: yes
  name: BuildAPI
